odom_model_type: diff
transform_tolerance: 0.2

use_map_topic: true
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_z: 0.0

odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map

gui_publish_rate: 10.0

laser_max_beams: 80
min_particles: 100
max_particles: 4000

kld_err: 0.05
kld_z: 0.99

odom_alpha1: 0.02
odom_alpha2: 0.07
odom_alpha3: 0.08
odom_alpha4: 0.02

laser_max_range: 4.9
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_model_type: likelihood_field

laser_likelihood_max_dist: 2.0

update_min_d: 0.08
update_min_a: 0.18

resample_interval: 1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

