obstacle_range: 2.5
raytrace_range: 3.0

#footprint: [[0.1,0.1],[0.1,-0.1],[-0.1,-0.1],[-0.1,0.1]]
robot_radius: 0.2

inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: link_laser, data_type: LaserScan, topic: /sensor/scan, marking: true, clearing: true}



