pub_map_odom_transform: true

map_frame: map
base_frame: base_link
odom_frame: base_link

use_tf_scan_transformation: true

map_resolution: 0.05
map_size: 2048
map_start_x: 0.5
map_start_y: 0.5
map_multi_res_levels: 2

update_factor_free: 0.4
update_factor_occupied: 0.9
map_update_distance_thresh: 0.1
laser_max_dist: 6.0
laser_min_dist: 0.25

advertise_map_service: true

scan_subscriber_queue_size: 5
scan_topic: sensor/scan
